server:
  servlet:
    encoding:
      charset: utf-8
      force: true
spring:
  datasource:
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      default_batch_fetch_size: 100
    open-in-view: false

logging:
  level:
    '[shop.mtcoding.servicebank]': DEBUG
    '[org.hibernate.type]': TRACE